### ISSUE TITLE
Support Dbug

### ISSUE THREAD

**Issue by lukeholder** [amacneil/craft-inspector#2]
Would be cool to support dbug

there is already a twig dbugextension: https://github.com/sunra/dbug-twig-extension

dbug for reference: http://dbug.ospinto.com/

**Comment by amacneil** [comment]
Hey, that looks cool. How do think we could best add it?

**Comment by lukeholder** [comment]
I'll give it a shot.

**Comment by lukeholder** [comment]
loos like they have a dependancy issue, left a bug report... will revisit later.
